# Generated by Django 5.2.13 on 2026-04-10 16:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('borrower', 'Borrower'), ('lender', 'Lender'), ('admin', 'Admin')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankSummaryDim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.borrowerprofile')),
                ('avg_monthly_credit', models.FloatField(default=0)),
                ('avg_monthly_debit', models.FloatField(default=0)),
                ('credit_debit_ratio', models.FloatField(default=0)),
                ('bounce_count_12m', models.IntegerField(default=0)),
                ('overdraft_usage_flag', models.BooleanField(default=False)),
                ('min_balance_breach_count', models.IntegerField(default=0)),
                ('avg_emi_bounce', models.FloatField(default=0)),
                ('actual_emi_ratio', models.FloatField(default=0)),
                ('liquidity_score', models.FloatField(default=0)),
                ('financial_stress_index', models.FloatField(default=0)),
                ('cc_min_pay_only_flag', models.BooleanField(default=False)),
                ('investment_debit_flag', models.BooleanField(default=False)),
                ('savings_behavior_score', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'dim_bank_summary',
            },
        ),
        migrations.CreateModel(
            name='DerivedSignalsDim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.borrowerprofile')),
                ('last_1y_itr_income_gap', models.FloatField(default=0)),
                ('actual_vs_declared_emi', models.FloatField(default=0)),
                ('gst_itr_consistency_score', models.FloatField(default=0)),
                ('multi_doc_anomaly_count', models.IntegerField(default=0)),
                ('repayment_capacity_score', models.FloatField(default=0)),
                ('financial_health_index', models.FloatField(default=0)),
                ('document_completeness_score', models.IntegerField(default=0)),
                ('composite_credit_score', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'dim_derived_signals',
            },
        ),
        migrations.CreateModel(
            name='ITRProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.borrowerprofile')),
                ('taxpayer_type', models.CharField(max_length=50)),
                ('income_source', models.CharField(max_length=100)),
                ('employer_category', models.CharField(max_length=100)),
                ('professional_exp_years', models.IntegerField(default=0)),
                ('gross_total_income_yr1', models.FloatField(default=0)),
                ('gross_total_income_yr2', models.FloatField(default=0)),
                ('gross_total_income_yr3', models.FloatField(default=0)),
                ('yoy_income_growth_rate', models.FloatField(default=0)),
                ('income_volatility_index', models.FloatField(default=0)),
                ('filing_delay_days', models.IntegerField(default=0)),
                ('section_80c_total', models.FloatField(default=0)),
                ('section_80d_premium', models.FloatField(default=0)),
                ('has_claimed_flag', models.BooleanField(default=False)),
                ('investment_assets_value', models.FloatField(default=0)),
                ('is_advanced_filer_flag', models.BooleanField(default=False)),
                ('declared_itr_ratio', models.FloatField(default=0)),
                ('asset_to_income_ratio', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'dim_itr_profile',
            },
        ),
        migrations.CreateModel(
            name='LoanSummaryDim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.borrowerprofile')),
                ('total_active_loans', models.IntegerField(default=0)),
                ('total_outstanding', models.FloatField(default=0)),
                ('total_monthly_emi', models.FloatField(default=0)),
                ('unsecured_debt_ratio', models.FloatField(default=0)),
                ('collateral_coverage_ratio', models.FloatField(default=0)),
                ('avg_dpd_90_ratio', models.FloatField(default=0)),
                ('debt_vintage_score', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'dim_loan_summary',
            },
        ),
        migrations.CreateModel(
            name='MasterMLTrainingTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.borrowerprofile')),
                ('is_default', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('income_stability_label', models.CharField(default='stable', max_length=30)),
                ('entry_stress_flag', models.BooleanField(default=False)),
                ('fraud_risk_score', models.FloatField(default=0)),
                ('recommended_loan_band', models.CharField(default='standard', max_length=30)),
            ],
            options={
                'db_table': 'master_ml_training_table',
            },
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankTransactionFact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_date', models.DateField()),
                ('txn_amount', models.FloatField()),
                ('txn_type', models.CharField(max_length=40)),
                ('txn_category', models.CharField(max_length=100)),
                ('balance_after', models.FloatField(default=0)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='api.borrowerprofile')),
            ],
            options={
                'db_table': 'fact_bank_txn',
            },
        ),
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=150)),
                ('institution_type', models.CharField(blank=True, max_length=100)),
                ('monthly_loan_volume', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=60)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('requested_tenure_months', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.borrowerprofile')),
                ('preferred_lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='api.lenderprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRegisterFact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=60)),
                ('lender_category', models.CharField(max_length=100)),
                ('original_principal', models.FloatField(default=0)),
                ('outstanding_principal', models.FloatField(default=0)),
                ('interest_rate_pa', models.FloatField(default=0)),
                ('tenure_remaining_months', models.IntegerField(default=0)),
                ('emi_amount', models.FloatField(default=0)),
                ('security_type', models.CharField(blank=True, max_length=80)),
                ('dpd_30_flag', models.BooleanField(default=False)),
                ('dpd_90_flag', models.BooleanField(default=False)),
                ('restructured_flag', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_register_facts', to='api.borrowerprofile')),
            ],
            options={
                'db_table': 'fact_loan_register',
            },
        ),
        migrations.CreateModel(
            name='GSTMonthlyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_month', models.CharField(max_length=7)),
                ('monthly_turnover', models.FloatField(default=0)),
                ('tax_claimed', models.FloatField(default=0)),
                ('tax_liability_gst', models.FloatField(default=0)),
                ('filing_delay_days', models.IntegerField(default=0)),
                ('nil_return_flag', models.BooleanField(default=False)),
                ('tax_sales_ratio', models.FloatField(default=0)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_monthly_facts', to='api.borrowerprofile')),
            ],
            options={
                'db_table': 'fact_gst_monthly',
                'unique_together': {('borrower', 'year_month')},
            },
        ),
    ]
